version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://shivangijain:indiA1234@cluster1.i2exfar.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - client

  client:
    build:
      context: ./client/game-app
      dockerfile: Dockerfile
    ports:
      - "5173:5000"
